Portfolio/Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PortfolioDatabase/', include('PortfolioDatabase.urls'))
]

Portfolio/PortfolioDatabase/urls.py
from . import views
from django.urls import path

app_name = 'Portfolio'
urlpatterns = [
    path('', views.index, name="index"),
    path('hobbies/', views.hobbies, name="hobbies"),
    path('contact/', views.contact, name="contact"),
    path('portfolio/', views.portfolio, name="portfolio"),
    path('home/', views.home, name="home"),
    path('hobbies/<int:hobby_id>', views.detail, name="detail"),
    path('portfolio/<int:portfolio_id>', views.portfolio_detail, name="portfolio_detail"),
]

Portfolio/PortfolioDatabase/models.py
from django.db import models


# Create your models here.
class Hobbies(models.Model):
    def __str__(self):
        return self.hobby_name+ "-" + self.hobby_description + " "

    hobby_name = models.CharField(max_length=200)
    hobby_description = models.CharField(max_length=200)
    hobby_image = models.CharField(max_length=500, default="https://sarkissian.pro/wp-content/uploads/2021/01/Jewelry-Inventory-1-256x256.png")


class Portfolio(models.Model):
    def __str__(self):
        return self.portfolio_item_name + "-" + \
            self.portfolio_item_description + " "
    portfolio_item_name = models.CharField(max_length=200)
    portfolio_item_description = models.CharField(max_length=200)
    portfolio_image = models.CharField(max_length=500, default="https://creazilla-store.fra1.digitaloceanspaces.com/cliparts/3162705/portfolio-clipart-md.png")

Portfolio/PortfolioDatabase/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Hobbies
from .models import Portfolio
from django.template import loader


# Create your views here.
def index(request):
    context = {}
    return render(request, 'PortfolioDatabase/index.html', context)

def home(request):
    context = {}
    return render(request, 'PortfolioDatabase/home.html', context)

def hobbies(request):
    hobby_list = Hobbies.objects.all()
    context = {
        'hobby_list': hobby_list,
    }
    return render(request, 'PortfolioDatabase/index.html', context)


def portfolio(request):
    portfolio_list = Portfolio.objects.all()
    context = {
        'portfolio_list': portfolio_list,
    }
    return render(request, 'PortfolioDatabase/portfolio.html', context)


def contact(request):
    context = {}
    return render(request, 'PortfolioDatabase/contact.html', context)


def detail(request, hobby_id):
    hobby = Hobbies.objects.get(pk=hobby_id)
    context = {
        'hobby': hobby
    }
    return render(request, 'PortfolioDatabase/detail.html', context)

def portfolio_detail(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    context = {
        'portfolio': portfolio
    }
    return render(request, 'PortfolioDatabase/portfolio_detail.html', context)

Portfolio/PortfolioDatabase/templates/PortfolioDatabase/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <a href="#" class = "navbar-brand">Portfolio App</a>
    <div class="navbar">
        <a href="#" class="nav-item">Add Item</a>
        <a href="#" class="nav-item">Delete Item</a>
        <a href="#" class="nav-item">View Item</a>
    </div>
  </nav>
{% block body %}
{% endblock %}
</body>
</html>

Portfolio/PortfolioDatabase/templates/PortfolioDatabase/contact.html
{% extends 'PortfolioDatabase/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">

</head>
<body>
{% block body %}
    <div class="intro" width="400px">
        <p>Email: gisselsantoyo@mail.weber.edu</p>
    </div>
{% endblock %}
</body>
</html>

Portfolio/PortfolioDatabase/templates/PortfolioDatabase/detail.html
{% extends 'PortfolioDatabase/base.html'%}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ hobby.hobby_image }}" class="hobby-img" height="300px" width="300px"/>
        </div>
        <div class="col-md-6">
            <h1 class="hobby-title">{{ hobby.hobby_name }}</h1>
            <h2>{{ hobby.hobby_description}}</h2>
        </div>
    </div>
</div>
{% endblock %}

Portfolio/PortfolioDatabase/templates/PortfolioDatabase/home.html
{% extends 'PortfolioDatabase/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">

</head>
<body>
{% block body %}
    <div class="intro" width="400px">
        <p>Hello, welcome to my django website. My name is gissel
        and I am studying CS at Weber State!</p>
    </div>
{% endblock %}
</body>
</html>

Portfolio/PortfolioDatabase/templates/PortfolioDatabase/index.html
{% extends 'PortfolioDatabase/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">

</head>
<body>
{% block body %}
{% for hobby in hobby_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="hobby-pics" height="200px" width="200px" src="{{ hobby.hobby_image }}"/>
        </div>
        <div class="col-md-4">
            <h3>{{ hobby.hobby_name }}</h3>
            <h5>{{ hobby.hobby_description }}</h5>
        </div>
        <div class="col-md-2">
            <a href="{% url 'Portfolio:detail' hobby.id %}" class="details_btn">Details</a>
        </div>
    </div>
{% endfor %}
{% endblock %}
</body>
</html>

Portfolio/PortfolioDatabase/templates/PortfolioDatabase/portfolio.html
{% extends 'PortfolioDatabase/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">

</head>
<body>
{% block body %}
{% for item in portfolio_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="portfolio-pics" height="200px" width="200px" src="{{ item.portfolio_image }}"/>
        </div>
        <div class="col-md-4">
            <h3>{{ item.portfolio_item_name }}</h3>
            <h5>{{ item.portfolio_item_description }}</h5>
        </div>
        <div class="col-md-2">
            <a href="{% url 'Portfolio:portfolio_detail' item.id %}" class="details_btn">Details</a>
        </div>
    </div>
{% endfor %}
{% endblock %}
</body>
</html>

Portfolio/PortfolioDatabase/templates/PortfolioDatabase/portfolio_detail.html
{% extends 'PortfolioDatabase/base.html'%}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ portfolio.portfolio_image }}" class="portfolio-img" height="300px" width="300px"/>
        </div>
        <div class="col-md-6">
            <h1 class="portfolio-title">{{ portfolio.portfolio_item_name }}</h1>
            <h2>{{ portfolio.portfolio_item_description}}</h2>
        </div>
    </div>
</div>
{% endblock %}